version: '3.8'

services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: soundscape-client
    ports:
      - "3000:3000"
    depends_on:
      - server
      - python_nlp
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: soundscape-server
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - python_nlp
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=soundscape_db
      - FREESOUND_API_KEY=${FREESOUND_API_KEY}
    volumes:
      - ./server:/app:delegated
      - server_node_modules:/app/node_modules
      - ./server/public:/app/public

  python_nlp:
    build:
      context: ./nlp
      dockerfile: Dockerfile
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - FREESOUND_API_KEY=${FREESOUND_API_KEY}
    container_name: soundscape-python
    ports:
      - "3002:3002"

  postgres:
    image: postgres:15-alpine
    container_name: soundscape-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: soundscape_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: soundscape-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  server_node_modules: